# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b221abd38a319f8159048cd749743e0a120007bfd36c849d35fc55ef61c14c4f59f2d2d2cc3c7de1bf5eb49c73b91b248077bf7cee7b99e0d8accb3c087ae20c

test:
  secret_key_base: e2466df4924924c39ee6366f9d15fd053b0e6fa72097efab7cc0c1f44defc28735647ce122344c6eb22b4d2e0864a5be7fa4c5f2bae3f007542c76f4b5a73304

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
